### ISSUE TITLE
Run as user 1000

### ISSUE THREAD

**Issue by johnt-softclouds** [bitnami/bitnami-docker-kibana#38]
Is there a way to run as another user besides 1001 or root?  What happens if the user account we want to use as user ID 1000 or 1010?

**Comment by miguelaeh** [comment]
Hi johnt-softclouds,

You can use `user` at the `docker-compose.yml` file. Try with this, I have test it and it works fine:

```
version: '2'

services:
  kibana:
    user: '1010'
    image: 'bitnami/kibana:latest'
    ports:
      - 5601:5601
    environment:
      - KIBANA_ELASTICSEARCH_URL=elasticsearch
    volumes:
      - 'kibana_data:/bitnami'
  elasticsearch:
    image: 'bitnami/elasticsearch:latest'
    ports:
      - 9200:9200
    volumes:
      - 'elasticsearch_data:/bitnami'
volumes:
  kibana_data:
    driver: local
  elasticsearch_data:
    driver: local
```

After the `docker-compose up` you can enter on the container:
```bash
$docker exec -it <container_id> bash
```

Where `<container_id>` comes from the `docker ps` command.
And execute `whoami`. You sholud see the 1010 user.
