### ISSUE TITLE
Kibana stuck at `Starting gosu...`

### ISSUE THREAD

**Issue by kienct89** [bitnami/bitnami-docker-kibana#42]
**Description**

Kibana stuck at `Starting gosu...`

**Steps to reproduce the issue:**

1. Install kibana using helm 

```
image:
  registry: docker.io
  repository: bitnami/kibana
  tag: 7.6.1-debian-10-r21
  pullPolicy: IfNotPresent
persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 10Gi
ingress:
      enabled: false
metrics:
      enabled: false
securityContext:
      enabled: true
      runAsUser: 1001
      fsGroup: 1001
      runAsNonRoot: true
volumePermissions:
      enabled: false
elasticsearch:
  hosts:
    - elasticsearch-coordinating-only
  port: 9200
```

**Describe the results you received:**

```
2020-03-29T02:41:43.328517529Z nami    INFO  Initializing kibana
2020-03-29T02:41:43.398941708Z kibana  INFO  ==> Found mounted kibana.yml configuration file
2020-03-29T02:41:43.474453844Z kibana  INFO 
2020-03-29T02:41:43.474890149Z kibana  INFO  ########################################################################
2020-03-29T02:41:43.475270453Z kibana  INFO   Installation parameters for kibana:
2020-03-29T02:41:43.47591136Z kibana  INFO     Persisted data and properties have been restored.
2020-03-29T02:41:43.476367465Z kibana  INFO     Any input specified will not take effect.
2020-03-29T02:41:43.476732169Z kibana  INFO   This installation requires no credentials.
2020-03-29T02:41:43.477126874Z kibana  INFO  ########################################################################
2020-03-29T02:41:43.477640379Z kibana  INFO 
2020-03-29T02:41:43.478492689Z nami    INFO  kibana successfully initialized
2020-03-29T02:41:43.525956714Z [0m[38;5;2mINFO [0m ==> Starting gosu...
```

**Describe the results you expected:**

Kibana should start successfully

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

- Platform: Azure AKS
- Kubernetes version: 1.15.7
- Helm chart info

```
repository: https://charts.bitnami.com/bitnami
name: kibana
version: 5.0.12
```

**Comment by Mauraza** [comment]
Hi @kienct89,

Do you run this command `helm install my-release bitnami/kibana --set elasticsearch.hosts[0]=elasticsearch-coordinating-only --set elasticsearch.port=9200` o something similar? In the logs don't appear the host of elastic.

**Comment by sventschui** [comment]
I just had the same issue and then found that kibana logs are not sent to stdout but rather `/opt/bitnami/kibana/logs/kibana.log`. Maybe the same applies to your installation?

**Comment by Mauraza** [comment]
Hi @sventschui,

Could you copy hear your logs? And tell me what step do you do? I want to be able to reproduce it.

**Comment by sventschui** [comment]
I just realised that once kibana is up and running logs are coming to stdout.

In my case the issue was that kibana failed to connect to elasticsearch. These early logs are not visible on stdout (which appears to hang on gosu) but rather go to `/opt/bitnami/kibana/logs/kibana.log` instead.

You can repro using the helm chart and the values @kienct89 provided. With the config it should not find any elasticsearch server on your system and therefore fail startup.

I think startup logs should go to stdout too, shouldn't they? I did not yet find time to dig into the entrypoint of this image to see why not all logs are directed to stdout but might find some time later.

**Comment by Mauraza** [comment]
Exactly, the next step is to connect with elasticsearch and stay in `starting gosu` because this step never comes. In the tests that I did, the logs appear. Maybe it could be a connection problem because, in the end, they do appear.

**Comment by kienct89** [comment]
`kubectl get svc`

```
elasticsearch-elasticsearch-coordinating-only   ClusterIP   10.0.107.116   <none>        9200/TCP   2d20h
```

kibana config

```
    elasticsearch:
      hosts:
        - elasticsearch-elasticsearch-coordinating-only
      port: 9200
```

I've pulled the running coordinating service and update kibana configuration, but I got the same issue still

**Comment by Mauraza** [comment]
Hi @kienct89,

could you try with this?
```
    elasticsearch:
      hosts:
        - elastic-elasticsearch-coordinating-only.default.svc.cluster.local
      port: 9200
```
